var N = null;var sourcesIndex = {};
sourcesIndex["circulate"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pliantdb"] = {"name":"","files":["cli.rs","lib.rs"]};
sourcesIndex["pliantdb_client"] = {"name":"","dirs":[{"name":"client","dirs":[{"name":"remote_database","files":["kv.rs","pubsub.rs"]}],"files":["quic_worker.rs","remote_database.rs","tungstenite_worker.rs"]}],"files":["client.rs","error.rs","lib.rs"]};
sourcesIndex["pliantdb_core"] = {"name":"","dirs":[{"name":"admin","files":["database.rs","group.rs","mod.rs","password_config.rs","role.rs","user.rs"]},{"name":"document","files":["revision.rs"]},{"name":"kv","dirs":[{"name":"implementation","files":["get.rs","increment.rs","namespaced.rs","set.rs"]}],"files":["timestamp.rs"]},{"name":"permissions","files":["mod.rs","pliant.rs"]},{"name":"schema","dirs":[{"name":"view","files":["map.rs"]}],"files":["collection.rs","mod.rs","names.rs","schematic.rs","view.rs"]}],"files":["connection.rs","custom_api.rs","document.rs","kv.rs","lib.rs","limits.rs","networking.rs","pubsub.rs","test_util.rs","transaction.rs"]};
sourcesIndex["pliantdb_jobs"] = {"name":"","dirs":[{"name":"manager","files":["jobs.rs","managed_job.rs"]}],"files":["lib.rs","manager.rs","task.rs","traits.rs"]};
sourcesIndex["pliantdb_local"] = {"name":"","dirs":[{"name":"database","files":["kv.rs","pubsub.rs"]},{"name":"storage","files":["kv.rs"]},{"name":"views","files":["integrity_scanner.rs","mapper.rs"]}],"files":["backup.rs","config.rs","database.rs","error.rs","lib.rs","open_trees.rs","storage.rs","tasks.rs","vault.rs","views.rs"]};
sourcesIndex["pliantdb_macros"] = {"name":"","files":["lib.rs"]};
sourcesIndex["pliantdb_server"] = {"name":"","dirs":[{"name":"cli","files":["certificate.rs","mod.rs","serve.rs"]},{"name":"server","files":["connected_client.rs","database.rs"]}],"files":["async_io_util.rs","backend.rs","config.rs","error.rs","lib.rs","server.rs","test_util.rs"]};
sourcesIndex["xtask"] = {"name":"","files":["main.rs"]};
createSourceSidebar();
